export const TYPING_PROMPTS: readonly string[] = [
  "The art of programming is the skill of telling another human what you want the computer to do. When you write code, you are not just instructing a machine, but communicating with future programmers who will read and maintain your work. Therefore, clarity and simplicity should always be prioritized over cleverness. Write code that is easy to understand, that tells a story, and that others can easily modify and extend. Remember that code is read far more often than it is written, so invest time in making your code readable. Use meaningful variable names, add helpful comments, and organize your code logically. These practices will make you a better programmer and make your code more valuable to your team.",
  "Debugging is twice as hard as writing code in the first place. Therefore, if you write the code as cleverly as possible, you are by definition not smart enough to debug it. The best approach is to keep your code simple and clear. When you encounter a bug, take time to understand what went wrong instead of just slapping a quick fix on it. Use debugging tools effectively, write tests to prevent regressions, and learn from each mistake you find.",
  "Software engineering is not just about writing code that works. It is about writing code that others can understand, maintain, and build upon. Good engineers think about edge cases, handle errors gracefully, and write code that is resilient to change. They document their decisions, communicate with their team, and take responsibility for the quality of what they produce.",
  "Testing is not a phase that comes after development. It is an integral part of the development process. Write tests as you code, not after. Tests serve as executable documentation of how your code should behave. They catch regressions early, give you confidence in refactoring, and make debugging easier when something breaks.",
  "Performance matters, but premature optimization is the root of all evil. First, write code that is correct and clear. Then, measure to find where the actual bottlenecks are. Finally, optimize those specific areas. Do not sacrifice readability for hypothetical performance gains. Profile, measure, optimize in that order.",
  "Version control is one of the most important tools in software development. Every change should have a clear commit message explaining the why, not just the what. Use branches strategically, review code before merging, and keep your history clean. A good commit history is invaluable when you need to understand how your codebase evolved.",
  "Writing secure code requires thinking like an attacker. Consider what would happen if someone tried to misuse your code. Validate all inputs, use parameterized queries to prevent SQL injection, handle sensitive data carefully, and keep your dependencies updated. Security is not a feature you add at the end; it must be built in from the beginning.",
  "Code reviews are where learning happens. When you review someone else's code, you see different approaches and solutions. When others review your code, you get valuable feedback. Be respectful, constructive, and thorough. The goal is to improve the code and help the team grow, not to show off or criticize.",
  "Documentation should be written for the person who will maintain your code in six months. That person might be future you. Include not just what the code does, but why you made certain choices. Explain complex algorithms, note edge cases, and update documentation when you change behavior. Good documentation reduces the time needed to understand and maintain code.",
  "The best code is code that solves the problem efficiently. But more importantly, it is code that your team understands and can maintain. Start with the simplest solution that works. Do not over-engineer or add features that are not needed. If the simple solution becomes a bottleneck, then you have data to justify optimizing it.",
  "Continuous learning is essential in software development. Technology changes rapidly, and new tools and techniques emerge constantly. Read books and blog posts, experiment with new languages and frameworks, and learn from the code you read. The best developers are curious and always working to improve their craft."
];

export function getRandomPrompt(): string {
  const randomIndex = Math.floor(Math.random() * TYPING_PROMPTS.length);
  return TYPING_PROMPTS[randomIndex];
}
